-- 1. Display all retailers from Madhya Pradesh

select *
from retailers
where state = 'MP';

-- 2. Show products with price greater than 1000

select product_name , price 
from products
where price > 1000;


-- 3. Find total number of customers

select count(*) as total_customers
from customers;

-- 4. Find average product price

select avg(price)as average_price
from products;

-- 5. Find highest paid employee

select employee_name , salary
from employees 
where salary = (
	select max(salary)
    from employees
    );

-- 6. Find total sales amount

select sum(total_amount) as total_sales
from orders;

-- 7. Display customer names with their orders

SELECT c.customer_name, o.order_id, o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

-- 8. Show retailer names with employee names

SELECT r.retailer_name, e.employee_name
FROM retailers r
JOIN employees e
ON r.retailer_id = e.retailer_id;

-- 9. Show product details for each order

SELECT o.order_id, p.product_name, od.quantity
FROM order_details od
JOIN products p
ON od.product_id = p.product_id
JOIN orders o
ON od.order_id = o.order_id;

-- 10. Count products by category

SELECT category, COUNT(*) AS total_products
FROM products
GROUP BY category;

-- 11. Find total revenue generated by each retailer

SELECT retailer_id, SUM(total_amount) AS revenue
FROM orders
GROUP BY retailer_id;

-- 12. Find second highest salary employee

SELECT employee_name, salary
FROM (
    SELECT employee_name, salary,
    DENSE_RANK() OVER (ORDER BY salary DESC) AS rnk
    FROM employees
) t
WHERE rnk = 2;

-- 13. Find customers who placed orders above 10000

SELECT c.customer_name, o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.total_amount > 10000;

-- 14. Show pending payments

SELECT *
FROM payments
WHERE payment_status = 'Pending';

-- 15. Find top selling product

SELECT product_id, SUM(quantity) AS total_sold
FROM order_details
GROUP BY product_id
ORDER BY total_sold DESC;

-- 16. Create a View for Customer Orders

CREATE VIEW customer_orders AS
SELECT c.customer_name, o.order_id, o.total_amount
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

-- 17. Create Stored Procedure

DELIMITER //

CREATE PROCEDURE GetAllProducts()
BEGIN
    SELECT * FROM products;
END //

DELIMITER ;

-- 18. Create Index for Faster Search

CREATE INDEX idx_product_name
ON products(product_name);

-- 19. Find monthly sales report

SELECT MONTH(order_date) AS month,
SUM(total_amount) AS monthly_sales
FROM orders
GROUP BY MONTH(order_date);


